<?php   $topbardataone = $DB->get_record('customhmp_top_bar',array('id'=>'1')); 
$topbardatatwo = $DB->get_record('customhmp_top_bar',array('id'=>'2')); 

?>
<header class="bg-dark-blue"><div class="container"><div class="row"><div class="col-md-12"><div class="top-social-icon"><ul class="nav navbar-right social-list"><li><a class="nav-link"href=""><i class="fa fa-facebook-square"></i></a></li><li><a class="nav-link"href=""><i class="fa fa-twitter"></i></a></li><li><a class="nav-link"href=""><i class="fa fa-instagram"></i></a></li></ul></div></div></div></div></header><div class="main_hader"><div class="container"><nav class="justify-content-between navbar navbar-light"><a class="navbar-brand"href="http://learning.preparetest.com/"><img src="http://learning.preparetest.com/blocks/customhomepage/assets/logo.svg"></a><ul class="loc nav navbar-right"><li class="item-flex nav-item"><a class="nav-link"><img src="http://learning.preparetest.com/theme/lambda/layout/image/Icon feather-phone-call.svg"><?=$topbardataone->content_one?><br><?=$topbardataone->content_two?></a></li><li class="item-flex"><a class="nav-link"><img src="http://learning.preparetest.com/theme/lambda/layout/image/Icon%20feather-map-pin.svg"><?=$topbardatatwo->content_one?></a></li><?php 
if (!isloggedin()) { ?><li class=" user"><a class="nav-link pr-0" href="<?php echo $CFG->wwwroot."/user-login/"; ?>"><i class="fas fa-user-tie mr-2"></i> <span class="login">Login / Register </span></a> </li>
<?php }else{ ?><li class=" user"><div class="dropdown u_er_drop"><button class="btn d_rop_dwn_user dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php	if(!empty($USER->picture) && $USER->picture!=0){ ?><img class="user_pr" src="<?php echo new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg')?>" alt="pro">
<?php }else{ ?><img  class="user_pr" src="<?php echo $CFG->wwwroot.'/blocks/searchdashboard/image/f1.png'; ?>" alt="pro"><?php } ?><span><?php echo $USER->firstname." ".$USER->lastname; ?></span></button><div class="dropdown-menu d_menu dropdown-menu-right menu  align-tr-br" id="action-menu-0-menu" data-rel="menu-content" aria-labelledby="action-menu-toggle-0" role="menu" data-align="tr-br" > <a href="<?php echo $CFG->wwwroot; ?>/blocks/searchdashboard/mytest.php" class="dropdown-item menu-action" role="menuitem" data-title="mymoodle,admin" aria-labelledby="actionmenuaction-1"> <img class="icon " alt="" aria-hidden="true" src="httpss://www.campustutr.com/theme/image.php/lambda/core/1628331714/i/dashboard"><span class="menu-action-text" id="actionmenuaction-1">My Test</span></a><div class="dropdown-divider" role="presentation"><span class="filler">&nbsp;</span></div><a href="<?php echo $CFG->wwwroot; ?>/user/edit.php?id=<?php echo $USER->id?>&returnto=profile" class="dropdown-item menu-action" role="menuitem" data-title="profile,moodle" aria-labelledby="actionmenuaction-2"><img class="icon " alt="" aria-hidden="true" src="httpss://www.campustutr.com/theme/image.php/lambda/core/1628331714/i/user"><span class="menu-action-text" id="actionmenuaction-2">Profile</span></a><a href="<?php echo $CFG->wwwroot."/login/change_password.php?id=1"; ?>" class="dropdown-item menu-action"><i class="fa fa-unlock-alt loc_k"  aria-hidden="true" style="color: #999999;
    font-size: 22px;"></i><span class="menu-action-text" id="actionmenuaction-6">Change Password</span></a> <a href="<?php echo $CFG->wwwroot."/login/logout.php?sesskey=".sesskey(); ?>" class="dropdown-item menu-action"><img class="icon " alt="" aria-hidden="true" src="httpss://www.campustutr.com/theme/image.php/lambda/core/1628331714/a/logout"><span class="menu-action-text" id="actionmenuaction-6">Log out</span> </a></div></div></li>
<?php } ?></ul></div></div></nav><section class="bg-img"><div class="container">
